list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake)

# Core dependencies
set(WITH_ZLIB OFF)
set(CMAKE_DISABLE_FIND_PACKAGE_ZLIB TRUE)
set(BUILD_SHARED_LIBS OFF)
set(BUILD_EXAMPLES OFF)
set(BUILD_BINDINGS OFF)
set(NO_ITUNES_HACKS ON)
set(utf8cpp_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/utfcpp/source" CACHE PATH "" FORCE)
set(BUILD_TESTING OFF)
set(FMT_MODULE OFF)

add_subdirectory(taglib SYSTEM)
add_subdirectory(miniz SYSTEM)
add_subdirectory(fmt EXCLUDE_FROM_ALL SYSTEM)
add_subdirectory(glaze SYSTEM)

if(TARGET miniz AND NOT TARGET miniz::miniz)
  add_library(miniz::miniz ALIAS miniz)
endif()

# GUI dependencies
if(ZINCBOX_GUI)
  option(NFD_PORTAL "" ON)
  set(NFD_PORTAL ON)

  set(FT_REQUIRE_ZLIB OFF)
  set(SPNG_SHARED OFF)
  set(SPNG_STATIC ON)
  set(SPNG_USE_MINIZ ON)
  set(GLM_BUILD_TESTS OFF)

  set(SDL_STATIC ON)
  set(SDL_SHARED OFF)
  set(SDL_X11_XSCRNSAVER OFF)
  set(SDL_X11_XTEST OFF)
  set(SDL_TEST_LIBRARY OFF)
  set(SDL_AUDIO OFF)
  set(SDL_GPU OFF)
  set(SDL_RENDER OFF)
  set(SDL_CAMERA OFF)
  set(SDL_JOYSTICK OFF)
  set(SDL_HAPTIC OFF)
  set(SDL_HIDAPI OFF)
  set(SDL_POWER OFF)
  set(SDL_SENSOR OFF)
  set(SDL_DIALOG OFF)
  set(SDL_NOTIFICATION OFF)

  add_subdirectory(freetype SYSTEM)
  add_subdirectory(nativefiledialog-extended SYSTEM)
  add_subdirectory(glm SYSTEM)
  add_subdirectory(stb_image SYSTEM)
  add_subdirectory(glad SYSTEM)
  add_subdirectory(SDL SYSTEM)
  add_subdirectory(cmrc SYSTEM)

  add_library(spng_static STATIC libspng/spng/spng.c)
  target_include_directories(spng_static PUBLIC libspng/spng)
  target_compile_definitions(spng_static PUBLIC SPNG_USE_MINIZ SPNG_STATIC)
  target_link_libraries(spng_static PRIVATE miniz::miniz)
endif()

# MPRIS dependencies
if(ZINCBOX_MPRIS)
  set(SDBUSCPP_BUILD_DOCS OFF)
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(SYSTEMD REQUIRED libsystemd)
  add_subdirectory(sdbus-cpp SYSTEM)
endif()
